Repository brain-tec/server-tools, pull requests merged in 2022-04, with the labels that each got.

#917 Syncing from upstream OCA/server-tools (10.0)
  README.md
  auth_totp/__manifest__.py
  html_text/__manifest__.py
  letsencrypt/__manifest__.py
  setup/auth_totp/setup.py
  setup/html_text/setup.py
  setup/letsencrypt/setup.py
Labels: 10.0

#918 Syncing from upstream OCA/server-tools (14.0)
  README.md
  sql_request_abstract/__manifest__.py
  sql_request_abstract/models/sql_request_mixin.py
Labels: 14.0

#919 Updating from latest OCA 15.0
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .t2d.yml
  README.md
  html_text/models/ir_fields_converter.py
  html_text/tests/test_extractor.py
Labels: 15.0.project_mi_465

#920 Syncing from upstream OCA/server-tools (13.0)
  .flake8
  base_view_inheritance_extension/README.rst
  base_view_inheritance_extension/__manifest__.py
  base_view_inheritance_extension/models/ir_ui_view.py
  base_view_inheritance_extension/readme/CONTRIBUTORS.rst
  base_view_inheritance_extension/static/description/index.html
  base_view_inheritance_extension/tests/test_base_view_inheritance_extension.py
  requirements.txt
Labels: 13.0

#922 Syncing from upstream OCA/server-tools (14.0)
  README.md
  jsonifier/README.rst
  jsonifier/__init__.py
  jsonifier/__manifest__.py
  jsonifier/static/description/icon.png
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/jsonifier/odoo/addons/jsonifier
  setup/jsonifier/setup.py
Labels: 14.0
