Repository brain-tec/server-tools, pull requests merged in 2022-03, with the labels that each got.

#885 Updating from latest OCA 15.0
  README.md
  base_view_inheritance_extension/README.rst
  base_view_inheritance_extension/__init__.py
  base_view_inheritance_extension/__manifest__.py
  base_view_inheritance_extension/demo/ir_ui_view.xml
  base_view_inheritance_extension/i18n/base_view_inheritance_extension.pot
  base_view_inheritance_extension/i18n/ca.po
  base_view_inheritance_extension/i18n/de.po
  base_view_inheritance_extension/i18n/es.po
  base_view_inheritance_extension/i18n/hr.po
  base_view_inheritance_extension/i18n/it.po
  base_view_inheritance_extension/i18n/sl.po
  base_view_inheritance_extension/i18n/tr.po
  base_view_inheritance_extension/models/__init__.py
  base_view_inheritance_extension/models/ir_ui_view.py
  base_view_inheritance_extension/readme/CONTRIBUTORS.rst
  base_view_inheritance_extension/readme/DESCRIPTION.rst
  base_view_inheritance_extension/readme/ROADMAP.rst
  base_view_inheritance_extension/readme/USAGE.rst
  base_view_inheritance_extension/static/description/icon.png
  base_view_inheritance_extension/static/description/index.html
  base_view_inheritance_extension/tests/__init__.py
  base_view_inheritance_extension/tests/test_base_view_inheritance_extension.py
  requirements.txt
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/base_view_inheritance_extension/odoo/addons/base_view_inheritance_extension
  setup/base_view_inheritance_extension/setup.py
Labels: 15.0.project_mi_465

#887 Syncing from upstream OCA/server-tools (14.0)
  README.md
  rpc_helper/README.rst
  rpc_helper/__init__.py
  rpc_helper/__manifest__.py
  rpc_helper/i18n/rpc_helper.pot
  rpc_helper/models/__init__.py
  rpc_helper/models/ir_model.py
  rpc_helper/patch.py
  rpc_helper/readme/CONFIGURATION.rst
  rpc_helper/readme/USAGE.rst
  rpc_helper/rpc_test_example.py
  rpc_helper/static/description/index.html
  rpc_helper/tests/test_xmlrpc.py
  rpc_helper/views/ir_model_views.xml
Labels: 14.0

#888 Syncing from upstream OCA/server-tools (14.0)
  README.md
  onchange_helper/__manifest__.py
  onchange_helper/models/base.py
Labels: 14.0

#889 Syncing from upstream OCA/server-tools (13.0)
  base_search_fuzzy/i18n/es_AR.po
  configuration_helper/i18n/es_AR.po
  html_image_url_extractor/i18n/es_AR.po
Labels: 13.0

#890 Syncing from upstream OCA/server-tools (14.0)
  base_report_auto_create_qweb/i18n/es_AR.po
  base_search_fuzzy/i18n/es_AR.po
  configuration_helper/i18n/es_AR.po
  html_image_url_extractor/i18n/es_AR.po
  letsencrypt/i18n/es_AR.po
Labels: 14.0

#892 Syncing from upstream OCA/server-tools (13.0)
  auditlog/i18n/es_AR.po
  sql_request_abstract/i18n/es_AR.po
Labels: 13.0

#893 Syncing from upstream OCA/server-tools (14.0)
  auditlog/i18n/es_AR.po
  sql_request_abstract/i18n/es_AR.po
Labels: 14.0

#894 Syncing from upstream OCA/server-tools (15.0)
  README.md
  base_search_fuzzy/i18n/es_AR.po
  fetchmail_notify_error_to_sender/README.rst
  fetchmail_notify_error_to_sender/__init__.py
  fetchmail_notify_error_to_sender/__manifest__.py
  fetchmail_notify_error_to_sender/data/email_template_data.xml
  fetchmail_notify_error_to_sender/i18n/ca.po
  fetchmail_notify_error_to_sender/i18n/de.po
  fetchmail_notify_error_to_sender/i18n/es.po
  fetchmail_notify_error_to_sender/i18n/fetchmail_notify_error_to_sender.pot
  fetchmail_notify_error_to_sender/i18n/fr.po
  fetchmail_notify_error_to_sender/i18n/hr.po
  fetchmail_notify_error_to_sender/i18n/it.po
  fetchmail_notify_error_to_sender/i18n/pt_BR.po
  fetchmail_notify_error_to_sender/i18n/pt_PT.po
  fetchmail_notify_error_to_sender/i18n/sl.po
  fetchmail_notify_error_to_sender/i18n/tr.po
  fetchmail_notify_error_to_sender/i18n/zh_CN.po
  fetchmail_notify_error_to_sender/models/__init__.py
  fetchmail_notify_error_to_sender/models/fetchmail.py
  fetchmail_notify_error_to_sender/models/mail_thread.py
  fetchmail_notify_error_to_sender/readme/CONFIGURE.rst
  fetchmail_notify_error_to_sender/readme/CONTRIBUTORS.rst
  fetchmail_notify_error_to_sender/readme/DESCRIPTION.rst
  fetchmail_notify_error_to_sender/static/description/icon.png
  fetchmail_notify_error_to_sender/static/description/index.html
  fetchmail_notify_error_to_sender/views/fetchmail_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/fetchmail_notify_error_to_sender/odoo/addons/fetchmail_notify_error_to_sender
  setup/fetchmail_notify_error_to_sender/setup.py
Labels: 15.0

#895 Syncing from upstream OCA/server-tools (13.0)
  base_exception/i18n/es_AR.po
Labels: 13.0

#896 Syncing from upstream OCA/server-tools (14.0)
  base_custom_info/i18n/it.po
  base_exception/i18n/es_AR.po
  base_exception/i18n/it.po
  base_kanban_stage/i18n/it.po
  base_report_auto_create_qweb/i18n/it.po
  base_search_fuzzy/i18n/it.po
  excel_import_export/i18n/it.po
  module_prototyper/i18n/it.po
Labels: 14.0

#897 Syncing from upstream OCA/server-tools (13.0)
  auto_backup/i18n/es_AR.po
  base_sparse_field_list_support/README.rst
  base_sparse_field_list_support/__init__.py
  base_sparse_field_list_support/__manifest__.py
  base_sparse_field_list_support/i18n/base_sparse_field_list_support.pot
  base_sparse_field_list_support/models/__init__.py
  base_sparse_field_list_support/models/fields.py
  base_sparse_field_list_support/readme/CONTRIBUTORS.rst
  base_sparse_field_list_support/readme/DESCRIPTION.rst
  base_sparse_field_list_support/static/description/icon.png
  base_sparse_field_list_support/static/description/index.html
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/base_sparse_field_list_support/odoo/addons/base_sparse_field_list_support
  setup/base_sparse_field_list_support/setup.py
Labels: 13.0

#898 Syncing from upstream OCA/server-tools (14.0)
  auto_backup/i18n/es_AR.po
  auto_backup/i18n/it.po
  sql_export/i18n/es_AR.po
Labels: 14.0

#900 Syncing from upstream OCA/server-tools (12.0)
  database_cleanup/__manifest__.py
  database_cleanup/static/description/icon.png
  database_cleanup/static/description/icon.svg
Labels: 12.0

#901 Syncing from upstream OCA/server-tools (13.0)
  base_sparse_field_list_support/__manifest__.py
Labels: 13.0

#903 Syncing from upstream OCA/server-tools (14.0)
  base_multi_image/i18n/es_AR.po
Labels: 14.0

#904 Syncing from upstream OCA/server-tools (14.0)
  sql_export/i18n/es_AR.po
Labels: 14.0

#905 Syncing from upstream OCA/server-tools (15.0)
  auditlog/i18n/es_AR.po
Labels: 15.0

#907 Syncing from upstream OCA/server-tools (15.0)
  README.md
  onchange_helper/README.rst
  onchange_helper/__init__.py
  onchange_helper/__manifest__.py
  onchange_helper/i18n/cs_CZ.po
  onchange_helper/i18n/de.po
  onchange_helper/i18n/es.po
  onchange_helper/i18n/fr.po
  onchange_helper/i18n/hr.po
  onchange_helper/i18n/onchange_helper.pot
  onchange_helper/i18n/sl.po
  onchange_helper/i18n/zh_CN.po
  onchange_helper/models/__init__.py
  onchange_helper/models/base.py
  onchange_helper/readme/CONTRIBUTORS.rst
  onchange_helper/readme/DESCRIPTION.rst
  onchange_helper/readme/USAGE.rst
  onchange_helper/static/description/icon.png
  onchange_helper/static/description/index.html
  onchange_helper/tests/__init__.py
  onchange_helper/tests/test_onchange_helper.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/onchange_helper/odoo/addons/onchange_helper
  setup/onchange_helper/setup.py
Labels: 15.0

#908 Syncing from upstream OCA/server-tools (15.0)
  README.md
  datetime_formatter/README.rst
  datetime_formatter/__init__.py
  datetime_formatter/__manifest__.py
  datetime_formatter/i18n/ar.po
  datetime_formatter/i18n/ca.po
  datetime_formatter/i18n/datetime_formatter.pot
  datetime_formatter/i18n/de.po
  datetime_formatter/i18n/es.po
  datetime_formatter/i18n/fr.po
  datetime_formatter/i18n/hr.po
  datetime_formatter/i18n/it.po
  datetime_formatter/i18n/nl_NL.po
  datetime_formatter/i18n/pt.po
  datetime_formatter/i18n/sl.po
  datetime_formatter/i18n/tr.po
  datetime_formatter/i18n/zh_CN.po
  datetime_formatter/models/__init__.py
  datetime_formatter/models/res_lang.py
  datetime_formatter/readme/CONTRIBUTORS.rst
  datetime_formatter/readme/DESCRIPTION.rst
  datetime_formatter/readme/USAGE.rst
  datetime_formatter/static/description/icon.png
  datetime_formatter/static/description/index.html
  datetime_formatter/tests/__init__.py
  datetime_formatter/tests/test_best_matcher.py
  datetime_formatter/tests/test_formatter.py
  module_auto_update/tests/sample_module/README.rst
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/datetime_formatter/odoo/addons/datetime_formatter
  setup/datetime_formatter/setup.py
Labels: 15.0

#909 Syncing from upstream OCA/server-tools (13.0)
  base_remote/i18n/es_AR.po
  onchange_helper/i18n/es_AR.po
Labels: 13.0

#910 Syncing from upstream OCA/server-tools (14.0)
  sql_export/i18n/es_AR.po
  sql_request_abstract/i18n/es_AR.po
Labels: 14.0

#913 Syncing from upstream OCA/server-tools (13.0)
  database_cleanup/i18n/es_AR.po
  datetime_formatter/i18n/es_AR.po
  scheduler_error_mailer/i18n/es_AR.po
Labels: 13.0

#914 Syncing from upstream OCA/server-tools (14.0)
  attachment_unindex_content/i18n/es_AR.po
  base_cron_exclusion/i18n/es_AR.po
  base_kanban_stage/i18n/es_AR.po
  base_remote/i18n/es_AR.po
  base_video_link/i18n/es_AR.po
  module_prototyper/i18n/es_AR.po
  onchange_helper/i18n/es_AR.po
Labels: 14.0
