Repository brain-tec/server-tools, pull requests merged in 2022-05, with the labels that each got.

#925 Syncing from upstream OCA/server-tools (14.0)
  README.md
  jsonifier/__manifest__.py
  jsonifier/models/models.py
Labels: 14.0

#926 Syncing from upstream OCA/server-tools (15.0)
  README.md
  upgrade_analysis/README.rst
  upgrade_analysis/__manifest__.py
  upgrade_analysis/readme/USAGE.rst
  upgrade_analysis/static/description/index.html
Labels: 15.0

#927 Syncing from upstream OCA/server-tools (12.0)
  company_country/__manifest__.py
  company_country/i18n/company_country.pot
  company_country/models/res_config.py
  company_country/tests/test_company_country.py
Labels: 12.0

#928 Syncing from upstream OCA/server-tools (14.0)
  excel_import_export/i18n/it.po
Labels: 14.0

#929 Merging 15.0 into 15.0.project_MI_465
  README.md
  upgrade_analysis/README.rst
  upgrade_analysis/__manifest__.py
  upgrade_analysis/readme/USAGE.rst
  upgrade_analysis/static/description/index.html
Labels: 15.0.project_mi_465

#930 Syncing from upstream OCA/server-tools (13.0)
  auditlog/i18n/es.po
  auto_backup/i18n/es.po
Labels: 13.0

#931 Syncing from upstream OCA/server-tools (13.0)
  auditlog/i18n/es_CL.po
  auto_backup/i18n/es_CL.po
Labels: 13.0

#932 Syncing from upstream OCA/server-tools (14.0)
  README.md
  base_exception/__manifest__.py
  base_exception/models/base_exception.py
Labels: 14.0

#934 Syncing from upstream OCA/server-tools (13.0)
  auto_backup/i18n/es.po
  auto_backup/i18n/es_CL.po
Labels: 13.0

#935 Syncing from upstream OCA/server-tools (14.0)
  README.md
  excel_import_export/__manifest__.py
  requirements.txt
Labels: 14.0
