Repository brain-tec/server-tools, pull requests merged in 2022-01, with the labels that each got.

#855 Syncing from upstream OCA/server-tools (12.0)
  excel_import_export/i18n/tr.po
Labels: 12.0

#856 Syncing from upstream OCA/server-tools (14.0)
  auto_backup/i18n/it.po
Labels: 14.0

#857 Syncing from upstream OCA/server-tools (14.0)
  auto_backup/i18n/it.po
  base_changeset/i18n/it.po
Labels: 14.0

#858 Syncing from upstream OCA/server-tools (12.0)
  base_multi_image/i18n/tr.po
  excel_import_export/i18n/tr.po
  excel_import_export_demo/i18n/tr.po
  fetchmail_notify_error_to_sender/i18n/tr.po
  html_text/i18n/tr.po
  module_auto_update/i18n/tr.po
Labels: 12.0

#860 Syncing from upstream OCA/server-tools (14.0)
  README.md
  base_time_window/__manifest__.py
  base_time_window/i18n/base_time_window.pot
  base_time_window/models/time_window_mixin.py
  test_base_time_window/__manifest__.py
  test_base_time_window/tests/test_base_time_window.py
Labels: 14.0

#861 Syncing from upstream OCA/server-tools (14.0)
  excel_import_export/i18n/it.po
Labels: 14.0

#862 Syncing from upstream OCA/server-tools (14.0)
  excel_import_export/i18n/it.po
Labels: 14.0

#863 Syncing from upstream OCA/server-tools (14.0)
  base_name_search_improved/i18n/it.po
  excel_import_export/i18n/it.po
Labels: 14.0

#864 Syncing from upstream OCA/server-tools (14.0)
  README.md
  base_jsonify/README.rst
  base_jsonify/__manifest__.py
  base_jsonify/models/ir_export.py
  base_jsonify/models/ir_exports_line.py
  base_jsonify/models/ir_exports_resolver.py
  base_jsonify/models/models.py
  base_jsonify/static/description/index.html
  base_jsonify/tests/test_get_parser.py
  base_jsonify/tests/test_ir_exports_line.py
Labels: 14.0

#865 Syncing from upstream OCA/server-tools (14.0)
  README.md
  base_changeset/README.rst
  base_changeset/__manifest__.py
  base_changeset/readme/CONFIGURE.rst
  base_changeset/readme/USAGE.rst
  base_changeset/static/description/index.html
  base_jsonify/__manifest__.py
  base_jsonify/models/models.py
  base_jsonify/tests/__init__.py
  base_jsonify/tests/test_helpers.py
  base_jsonify/tests/test_ir_exports_line.py
Labels: 14.0

#867 Syncing from upstream OCA/server-tools (14.0)
  README.md
  base_jsonify/README.rst
  base_jsonify/__manifest__.py
  base_jsonify/i18n/base_jsonify.pot
  base_jsonify/i18n/zh_CN.po
  base_jsonify/models/__init__.py
  base_jsonify/models/ir_exports.py
  base_jsonify/models/ir_exports_line.py
  base_jsonify/models/ir_exports_resolver.py
  base_jsonify/models/models.py
  base_jsonify/models/utils.py
  base_jsonify/readme/DESCRIPTION.rst
  base_jsonify/static/description/index.html
  base_jsonify/tests/test_ir_exports_line.py
Labels: 14.0

#868 Syncing from upstream OCA/server-tools (12.0)
  scheduler_error_mailer/__manifest__.py
  scheduler_error_mailer/data/ir_cron_email_tpl.xml
  scheduler_error_mailer/i18n/de.po
  scheduler_error_mailer/i18n/es.po
  scheduler_error_mailer/i18n/fr.po
  scheduler_error_mailer/i18n/hr.po
  scheduler_error_mailer/i18n/pt.po
  scheduler_error_mailer/i18n/pt_BR.po
  scheduler_error_mailer/i18n/scheduler_error_mailer.pot
  scheduler_error_mailer/i18n/sl.po
  scheduler_error_mailer/i18n/zh_CN.po
  scheduler_error_mailer/migrations/12.0.1.2.0/post-migration.py
Labels: 12.0

#869 Syncing from upstream OCA/server-tools (13.0)
  scheduler_error_mailer/README.rst
  scheduler_error_mailer/__init__.py
  scheduler_error_mailer/__manifest__.py
  scheduler_error_mailer/data/ir_cron_email_tpl.xml
  scheduler_error_mailer/demo/ir_cron_demo.xml
  scheduler_error_mailer/i18n/de.po
  scheduler_error_mailer/i18n/es.po
  scheduler_error_mailer/i18n/fr.po
  scheduler_error_mailer/i18n/hr.po
  scheduler_error_mailer/i18n/pt.po
  scheduler_error_mailer/i18n/pt_BR.po
  scheduler_error_mailer/i18n/scheduler_error_mailer.pot
  scheduler_error_mailer/i18n/sl.po
  scheduler_error_mailer/i18n/zh_CN.po
  scheduler_error_mailer/images/scheduler_error_mailer.jpg
  scheduler_error_mailer/models/__init__.py
  scheduler_error_mailer/models/ir_cron.py
  scheduler_error_mailer/readme/CONFIGURE.rst
  scheduler_error_mailer/readme/CONTRIBUTORS.rst
  scheduler_error_mailer/readme/DESCRIPTION.rst
  scheduler_error_mailer/static/description/icon.png
  scheduler_error_mailer/static/description/index.html
  scheduler_error_mailer/views/ir_cron.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/scheduler_error_mailer/odoo/addons/scheduler_error_mailer
  setup/scheduler_error_mailer/setup.py
Labels: 13.0

#871 Pre-commit bugfixing for auditlog
  auditlog/models/log.py
  auditlog/models/rule.py
  auditlog/tests/test_auditlog.py
  auditlog/views/auditlog_view.xml
Labels: bug, 15.0.project_mi_465

#870 Updating from latest OCA 15.0
  README.md
  base_cron_exclusion/README.rst
  base_cron_exclusion/__init__.py
  base_cron_exclusion/__manifest__.py
  base_cron_exclusion/i18n/base_cron_exclusion.pot
  base_cron_exclusion/i18n/cs_CZ.po
  base_cron_exclusion/i18n/es.po
  base_cron_exclusion/i18n/fr.po
  base_cron_exclusion/i18n/zh_CN.po
  base_cron_exclusion/models/__init__.py
  base_cron_exclusion/models/ir_cron.py
  base_cron_exclusion/readme/CONTRIBUTORS.rst
  base_cron_exclusion/readme/DESCRIPTION.rst
  base_cron_exclusion/readme/USAGE.rst
  base_cron_exclusion/static/description/icon.png
  base_cron_exclusion/static/description/index.html
  base_cron_exclusion/views/ir_cron_view.xml
  fetchmail_incoming_log/README.rst
  fetchmail_incoming_log/__init__.py
  fetchmail_incoming_log/__manifest__.py
  fetchmail_incoming_log/i18n/ca.po
  fetchmail_incoming_log/i18n/de.po
  fetchmail_incoming_log/i18n/es.po
  fetchmail_incoming_log/i18n/fetchmail_incoming_log.pot
  fetchmail_incoming_log/i18n/fr.po
  fetchmail_incoming_log/i18n/it.po
  fetchmail_incoming_log/i18n/pt_BR.po
  fetchmail_incoming_log/i18n/pt_PT.po
  fetchmail_incoming_log/i18n/sl.po
  fetchmail_incoming_log/i18n/tr.po
  fetchmail_incoming_log/models/__init__.py
  fetchmail_incoming_log/models/mail_thread.py
  fetchmail_incoming_log/readme/CONTRIBUTORS.rst
  fetchmail_incoming_log/readme/DESCRIPTION.rst
  fetchmail_incoming_log/static/description/icon.png
  fetchmail_incoming_log/static/description/index.html
  fetchmail_incoming_log/tests/__init__.py
  fetchmail_incoming_log/tests/test_fetchmail_incoming_log.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/base_cron_exclusion/odoo/addons/base_cron_exclusion
  setup/base_cron_exclusion/setup.py
  setup/fetchmail_incoming_log/odoo/addons/fetchmail_incoming_log
  setup/fetchmail_incoming_log/setup.py
Labels: 15.0.project_mi_465
