Repository brain-tec/server-tools, pull requests merged in 2022-08, with the labels that each got.

#951 Syncing from upstream OCA/server-tools (14.0)
  README.md
  base_search_fuzzy/README.rst
  base_search_fuzzy/__manifest__.py
  base_search_fuzzy/readme/USAGE.rst
  base_search_fuzzy/static/description/index.html
Labels: 14.0

#952 Updating from latest OCA 15.0
  README.md
  onchange_helper/__manifest__.py
  onchange_helper/models/base.py
Labels: 15.0.project_mi_465

#954 Syncing from upstream OCA/server-tools (12.0)
  module_change_auto_install/README.rst
  module_change_auto_install/__init__.py
  module_change_auto_install/__manifest__.py
  module_change_auto_install/i18n/module_change_auto_install.pot
  module_change_auto_install/patch.py
  module_change_auto_install/readme/CONFIGURE.rst
  module_change_auto_install/readme/CONTRIBUTORS.rst
  module_change_auto_install/readme/DESCRIPTION.rst
  module_change_auto_install/readme/DEVELOP.rst
  module_change_auto_install/readme/INSTALL.rst
  module_change_auto_install/static/description/icon.png
  module_change_auto_install/static/description/index.html
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/module_change_auto_install/odoo/addons/module_change_auto_install
  setup/module_change_auto_install/setup.py
Labels: 12.0

#955 Syncing from upstream OCA/server-tools (15.0)
  README.md
  base_exception/__manifest__.py
  base_exception/tests/purchase_test.py
  base_exception/tests/test_base_exception.py
  test-requirements.txt
Labels: 15.0

#956 Syncing from upstream OCA/server-tools (13.0)
  attachment_unindex_content/i18n/es_AR.po
  autovacuum_message_attachment/i18n/autovacuum_message_attachment.pot
  autovacuum_message_attachment/i18n/fr.po
  base_changeset/i18n/base_changeset.pot
  base_changeset/i18n/es.po
  base_custom_info/i18n/es_AR.po
  base_name_search_improved/i18n/base_name_search_improved.pot
  base_name_search_improved/i18n/ca.po
  base_name_search_improved/i18n/de.po
  base_name_search_improved/i18n/es.po
  base_name_search_improved/i18n/es_ES.po
  base_name_search_improved/i18n/eu.po
  base_name_search_improved/i18n/fi.po
  base_name_search_improved/i18n/fr.po
  base_name_search_improved/i18n/hr.po
  base_name_search_improved/i18n/hr_HR.po
  base_name_search_improved/i18n/it.po
  base_name_search_improved/i18n/nb_NO.po
  base_name_search_improved/i18n/nl.po
  base_name_search_improved/i18n/pt_BR.po
  base_name_search_improved/i18n/sl.po
  base_name_search_improved/i18n/tr.po
  base_name_search_improved/i18n/tr_TR.po
  base_name_search_improved/i18n/zh_CN.po
  html_text/i18n/es_AR.po
  iap_alternative_provider/i18n/es_AR.po
Labels: 13.0

#957 Syncing from upstream OCA/server-tools (14.0)
  base_custom_info/i18n/es_AR.po
Labels: 14.0

#958 Syncing from upstream OCA/server-tools (13.0)
  fetchmail_incoming_log/i18n/es_AR.po
Labels: 13.0

#960 Syncing from upstream OCA/server-tools (15.0)
  README.md
  dbfilter_from_header/README.rst
  dbfilter_from_header/__init__.py
  dbfilter_from_header/__manifest__.py
  dbfilter_from_header/i18n/dbfilter_from_header.pot
  dbfilter_from_header/i18n/zh_CN.po
  dbfilter_from_header/override.py
  dbfilter_from_header/readme/CONFIGURE.rst
  dbfilter_from_header/readme/CONTRIBUTORS.rst
  dbfilter_from_header/readme/DESCRIPTION.rst
  dbfilter_from_header/readme/INSTALL.rst
  dbfilter_from_header/readme/USAGE.rst
  dbfilter_from_header/static/description/icon.png
  dbfilter_from_header/static/description/index.html
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/dbfilter_from_header/odoo/addons/dbfilter_from_header
  setup/dbfilter_from_header/setup.py
Labels: 15.0

#961 Syncing from upstream OCA/server-tools (13.0)
  dbfilter_from_header/i18n/es_AR.po
  excel_import_export/i18n/es_AR.po
Labels: 13.0

#962 Syncing from upstream OCA/server-tools (14.0)
  excel_import_export/i18n/es_AR.po
Labels: 14.0

#963 Syncing from upstream OCA/server-tools (14.0)
  auto_backup/i18n/hr.po
Labels: 14.0

#964 Syncing from upstream OCA/server-tools (12.0)
  base_import_module_group/__manifest__.py
Labels: 12.0

#965 Syncing from upstream OCA/server-tools (14.0)
  base_custom_info/i18n/pt.po
  base_generate_code/i18n/hr.po
Labels: 14.0

#968 Backmerging 15.0 into 15.0.project_MI_465
  README.md
  dbfilter_from_header/README.rst
  dbfilter_from_header/__init__.py
  dbfilter_from_header/__manifest__.py
  dbfilter_from_header/i18n/dbfilter_from_header.pot
  dbfilter_from_header/i18n/zh_CN.po
  dbfilter_from_header/override.py
  dbfilter_from_header/readme/CONFIGURE.rst
  dbfilter_from_header/readme/CONTRIBUTORS.rst
  dbfilter_from_header/readme/DESCRIPTION.rst
  dbfilter_from_header/readme/INSTALL.rst
  dbfilter_from_header/readme/USAGE.rst
  dbfilter_from_header/static/description/icon.png
  dbfilter_from_header/static/description/index.html
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/dbfilter_from_header/odoo/addons/dbfilter_from_header
  setup/dbfilter_from_header/setup.py
Labels: 15.0.project_mi_465
