Repository brain-tec/server-tools, pull requests merged in 2022-02, with the labels that each got.

#872 Syncing from upstream OCA/server-tools (14.0)
  README.md
  base_changeset/__manifest__.py
  base_changeset/i18n/base_changeset.pot
  base_changeset/i18n/es.po
  base_changeset/i18n/it.po
  base_changeset/models/changeset_field_rule.py
  base_changeset/models/record_changeset_change.py
  base_changeset/tests/test_changeset_flow.py
  base_changeset/views/changeset_field_rule_views.xml
  base_search_fuzzy/i18n/pt_BR.po
  bus_alt_connection/README.rst
  bus_alt_connection/__init__.py
  bus_alt_connection/__manifest__.py
  bus_alt_connection/i18n/bus_alt_connection.pot
  bus_alt_connection/models/__init__.py
  bus_alt_connection/models/bus.py
  bus_alt_connection/readme/CONFIGURE.rst
  bus_alt_connection/readme/CONTRIBUTORS.rst
  bus_alt_connection/readme/DESCRIPTION.rst
  bus_alt_connection/readme/INSTALL.rst
  bus_alt_connection/static/description/icon.png
  bus_alt_connection/static/description/index.html
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/bus_alt_connection/odoo/addons/bus_alt_connection
  setup/bus_alt_connection/setup.py
  sql_request_abstract/i18n/pt_BR.po
Labels: 14.0

#873 Syncing from upstream OCA/server-tools (15.0)
  README.md
  html_text/README.rst
  html_text/__init__.py
  html_text/__manifest__.py
  html_text/i18n/ca.po
  html_text/i18n/de.po
  html_text/i18n/es.po
  html_text/i18n/es_ES.po
  html_text/i18n/hr.po
  html_text/i18n/html_text.pot
  html_text/i18n/it.po
  html_text/i18n/tr.po
  html_text/i18n/zh_CN.po
  html_text/models/__init__.py
  html_text/models/ir_fields_converter.py
  html_text/readme/CONTRIBUTORS.rst
  html_text/readme/DESCRIPTION.rst
  html_text/readme/ROADMAP.rst
  html_text/readme/USAGE.rst
  html_text/static/description/icon.png
  html_text/static/description/index.html
  html_text/tests/__init__.py
  html_text/tests/test_extractor.py
  requirements.txt
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/html_text/odoo/addons/html_text
  setup/html_text/setup.py
Labels: 15.0

#875 Syncing from upstream OCA/server-tools (15.0)
  README.md
  module_auto_update/README.rst
  module_auto_update/__init__.py
  module_auto_update/__manifest__.py
  module_auto_update/addon_hash.py
  module_auto_update/hooks.py
  module_auto_update/i18n/ca.po
  module_auto_update/i18n/cs_CZ.po
  module_auto_update/i18n/de.po
  module_auto_update/i18n/es.po
  module_auto_update/i18n/es_MX.po
  module_auto_update/i18n/fr.po
  module_auto_update/i18n/hr.po
  module_auto_update/i18n/it.po
  module_auto_update/i18n/module_auto_update.pot
  module_auto_update/i18n/nl_NL.po
  module_auto_update/i18n/pt_BR.po
  module_auto_update/i18n/sl.po
  module_auto_update/i18n/tr.po
  module_auto_update/i18n/zh_CN.po
  module_auto_update/models/__init__.py
  module_auto_update/models/module.py
  module_auto_update/readme/CONFIGURE.rst
  module_auto_update/readme/CONTRIBUTORS.rst
  module_auto_update/readme/DESCRIPTION.rst
  module_auto_update/readme/USAGE.rst
  module_auto_update/static/description/icon.png
  module_auto_update/static/description/index.html
  module_auto_update/tests/__init__.py
  module_auto_update/tests/sample_module/README.rst
  module_auto_update/tests/sample_module/data/f1.xml
  module_auto_update/tests/sample_module/data/f2.xml
  module_auto_update/tests/sample_module/i18n/en.po
  module_auto_update/tests/sample_module/i18n/en_US.po
  module_auto_update/tests/sample_module/i18n/fr.po
  module_auto_update/tests/sample_module/i18n/fr_BE.po
  module_auto_update/tests/sample_module/i18n/test.pot
  module_auto_update/tests/sample_module/i18n_extra/en.po
  module_auto_update/tests/sample_module/i18n_extra/fr.po
  module_auto_update/tests/sample_module/i18n_extra/nl_NL.po
  module_auto_update/tests/sample_module/models/stuff.py
  module_auto_update/tests/sample_module/models/stuff.pyc
  module_auto_update/tests/sample_module/models/stuff.pyo
  module_auto_update/tests/sample_module/static/src/some.js
  module_auto_update/tests/test_addon_hash.py
  module_auto_update/tests/test_module.py
  module_auto_update/views/ir_module_module.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/module_auto_update/odoo/addons/module_auto_update
  setup/module_auto_update/setup.py
Labels: 15.0

#876 [bt#16913] remove object parameter from ir.values create vals
  mass_editing/models/mass_object.py
Labels: bt_2900

#878 Syncing from upstream OCA/server-tools (14.0)
  attachment_unindex_content/i18n/ca.po
  auto_backup/i18n/ca.po
  autovacuum_message_attachment/i18n/ca.po
  base_changeset/i18n/ca.po
  base_cron_exclusion/i18n/ca.po
  base_jsonify/i18n/ca.po
  excel_import_export_demo/i18n/ca.po
  fetchmail_notify_error_to_sender_test/i18n/ca.po
  iap_alternative_provider/i18n/ca.po
  module_change_auto_install/i18n/ca.po
  onchange_helper/i18n/ca.po
  scheduler_error_mailer/i18n/ca.po
  sentry/i18n/ca.po
  sequence_python/i18n/ca.po
  slow_statement_logger/i18n/ca.po
  sql_export_excel/i18n/ca.po
  sql_export_mail/i18n/ca.po
  test_base_time_window/i18n/ca.po
  upgrade_analysis/i18n/ca.po
Labels: 14.0

#880 Syncing from upstream OCA/server-tools (15.0)
  README.md
  base_view_inheritance_extension/README.rst
  base_view_inheritance_extension/__init__.py
  base_view_inheritance_extension/__manifest__.py
  base_view_inheritance_extension/demo/ir_ui_view.xml
  base_view_inheritance_extension/i18n/base_view_inheritance_extension.pot
  base_view_inheritance_extension/i18n/ca.po
  base_view_inheritance_extension/i18n/de.po
  base_view_inheritance_extension/i18n/es.po
  base_view_inheritance_extension/i18n/hr.po
  base_view_inheritance_extension/i18n/it.po
  base_view_inheritance_extension/i18n/sl.po
  base_view_inheritance_extension/i18n/tr.po
  base_view_inheritance_extension/models/__init__.py
  base_view_inheritance_extension/models/ir_ui_view.py
  base_view_inheritance_extension/readme/CONTRIBUTORS.rst
  base_view_inheritance_extension/readme/DESCRIPTION.rst
  base_view_inheritance_extension/readme/ROADMAP.rst
  base_view_inheritance_extension/readme/USAGE.rst
  base_view_inheritance_extension/static/description/icon.png
  base_view_inheritance_extension/static/description/index.html
  base_view_inheritance_extension/tests/__init__.py
  base_view_inheritance_extension/tests/test_base_view_inheritance_extension.py
  requirements.txt
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/base_view_inheritance_extension/odoo/addons/base_view_inheritance_extension
  setup/base_view_inheritance_extension/setup.py
Labels: 15.0

#882 Syncing from upstream OCA/server-tools (13.0)
  autovacuum_message_attachment/i18n/autovacuum_message_attachment.pot
  autovacuum_message_attachment/i18n/fr.po
  base_changeset/i18n/base_changeset.pot
  base_changeset/i18n/es.po
  base_name_search_improved/i18n/base_name_search_improved.pot
  base_name_search_improved/i18n/ca.po
  base_name_search_improved/i18n/de.po
  base_name_search_improved/i18n/es.po
  base_name_search_improved/i18n/es_ES.po
  base_name_search_improved/i18n/eu.po
  base_name_search_improved/i18n/fi.po
  base_name_search_improved/i18n/fr.po
  base_name_search_improved/i18n/hr.po
  base_name_search_improved/i18n/hr_HR.po
  base_name_search_improved/i18n/it.po
  base_name_search_improved/i18n/nb_NO.po
  base_name_search_improved/i18n/nl.po
  base_name_search_improved/i18n/pt_BR.po
  base_name_search_improved/i18n/sl.po
  base_name_search_improved/i18n/tr.po
  base_name_search_improved/i18n/tr_TR.po
  base_name_search_improved/i18n/zh_CN.po
  company_country/__init__.py
  company_country/__manifest__.py
  company_country/data/res_config.xml
  company_country/i18n/company_country.pot
  company_country/i18n/es.po
  company_country/models/__init__.py
  company_country/models/res_config.py
  company_country/tests/__init__.py
  company_country/tests/test_company_country.py
Labels: 13.0

#883 Syncing from upstream OCA/server-tools (14.0)
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .travis.yml
  README.md
  test-requirements.txt
Labels: 14.0
