Repository brain-tec/server-tools, pull requests merged in 2023-01, with the labels that each got.

#1046 Syncing from upstream OCA/server-tools (8.0)
  auto_backup/i18n/it.po
Labels: 8.0

#1047 Syncing from upstream OCA/server-tools (9.0)
  auto_backup/i18n/it.po
Labels: 9.0

#1048 Syncing from upstream OCA/server-tools (10.0)
  auto_backup/i18n/it.po
  fetchmail_notify_error_to_sender/i18n/it.po
Labels: 10.0

#1049 Syncing from upstream OCA/server-tools (11.0)
  auto_backup/i18n/it.po
  fetchmail_notify_error_to_sender/i18n/it.po
Labels: 11.0

#1050 Syncing from upstream OCA/server-tools (12.0)
  auto_backup/i18n/it.po
  fetchmail_notify_error_to_sender/i18n/it.po
Labels: 12.0

#1051 Syncing from upstream OCA/server-tools (13.0)
  auto_backup/i18n/it.po
  fetchmail_notify_error_to_sender/i18n/it.po
Labels: 13.0

#1052 Syncing from upstream OCA/server-tools (8.0)
  base_search_fuzzy/i18n/it.po
  base_user_role/i18n/it.po
  import_odbc/i18n/it.po
  module_uninstall_check/i18n/it.po
Labels: 8.0

#1054 Syncing from upstream OCA/server-tools (10.0)
  base_kanban_stage/i18n/it.po
Labels: 10.0

#1055 Syncing from upstream OCA/server-tools (11.0)
  base_exception/i18n/it.po
  database_cleanup/i18n/it.po
Labels: 11.0

#1056 Syncing from upstream OCA/server-tools (12.0)
  base_exception/i18n/it.po
  base_kanban_stage/i18n/it.po
Labels: 12.0

#1057 Syncing from upstream OCA/server-tools (13.0)
  base_exception/i18n/it.po
  database_cleanup/i18n/it.po
  module_analysis/i18n/it.po
Labels: 13.0

#1058 Syncing from upstream OCA/server-tools (14.0)
  auditlog/i18n/es_AR.po
  auto_backup/i18n/it.po
  base_kanban_stage/i18n/it.po
  base_sequence_option/i18n/it.po
  database_cleanup/i18n/it.po
  excel_import_export/i18n/it.po
  fetchmail_notify_error_to_sender/i18n/it.po
Labels: 14.0

#1061 Syncing from upstream OCA/server-tools (16.0)
  README.md
  base_cron_exclusion/README.rst
  base_cron_exclusion/__init__.py
  base_cron_exclusion/__manifest__.py
  base_cron_exclusion/i18n/base_cron_exclusion.pot
  base_cron_exclusion/i18n/cs_CZ.po
  base_cron_exclusion/i18n/es.po
  base_cron_exclusion/i18n/es_AR.po
  base_cron_exclusion/i18n/fr.po
  base_cron_exclusion/i18n/zh_CN.po
  base_cron_exclusion/models/__init__.py
  base_cron_exclusion/models/ir_cron.py
  base_cron_exclusion/readme/CONTRIBUTORS.rst
  base_cron_exclusion/readme/DESCRIPTION.rst
  base_cron_exclusion/readme/USAGE.rst
  base_cron_exclusion/static/description/icon.png
  base_cron_exclusion/static/description/index.html
  base_cron_exclusion/views/ir_cron_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/base_cron_exclusion/odoo/addons/base_cron_exclusion
  setup/base_cron_exclusion/setup.py
Labels: 16.0

#1062 Syncing from upstream OCA/server-tools (14.0)
  base_time_parameter/i18n/pt.po
Labels: 14.0

#1063 Syncing from upstream OCA/server-tools (14.0)
  README.md
  mail_cleanup/README.rst
  mail_cleanup/__init__.py
  mail_cleanup/__manifest__.py
  mail_cleanup/i18n/ca.po
  mail_cleanup/i18n/de.po
  mail_cleanup/i18n/es.po
  mail_cleanup/i18n/fr.po
  mail_cleanup/i18n/hr.po
  mail_cleanup/i18n/it.po
  mail_cleanup/i18n/mail_cleanup.pot
  mail_cleanup/i18n/pt_BR.po
  mail_cleanup/i18n/sl.po
  mail_cleanup/i18n/tr.po
  mail_cleanup/i18n/zh_CN.po
  mail_cleanup/models/__init__.py
  mail_cleanup/models/fetchmail_server.py
  mail_cleanup/readme/CONFIGURE.rst
  mail_cleanup/readme/CONTRIBUTORS.rst
  mail_cleanup/readme/CREDITS.rst
  mail_cleanup/readme/DESCRIPTION.rst
  mail_cleanup/static/description/icon.png
  mail_cleanup/static/description/index.html
  mail_cleanup/views/mail_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/mail_cleanup/odoo/addons/mail_cleanup
  setup/mail_cleanup/setup.py
Labels: 14.0

#1065 Syncing from upstream OCA/server-tools (16.0)
  README.md
  base_technical_user/README.rst
  base_technical_user/__init__.py
  base_technical_user/__manifest__.py
  base_technical_user/i18n/ar.po
  base_technical_user/i18n/base_technical_user.pot
  base_technical_user/i18n/de.po
  base_technical_user/i18n/es.po
  base_technical_user/i18n/fr.po
  base_technical_user/i18n/hr.po
  base_technical_user/i18n/it.po
  base_technical_user/i18n/nl_NL.po
  base_technical_user/i18n/pt.po
  base_technical_user/i18n/zh_CN.po
  base_technical_user/models/__init__.py
  base_technical_user/models/models.py
  base_technical_user/models/res_company.py
  base_technical_user/readme/CONTRIBUTORS.rst
  base_technical_user/readme/DESCRIPTION.rst
  base_technical_user/readme/USAGE.rst
  base_technical_user/static/description/icon.png
  base_technical_user/static/description/index.html
  base_technical_user/tests/__init__.py
  base_technical_user/tests/test_sudo_tech.py
  base_technical_user/views/res_company_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/base_technical_user/odoo/addons/base_technical_user
  setup/base_technical_user/setup.py
Labels: 16.0

#1067 Syncing from upstream OCA/server-tools (14.0)
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  README.md
  database_cleanup/__manifest__.py
  database_cleanup/i18n/en.po
  module_auto_update/__manifest__.py
  module_auto_update/tests/sample_module/i18n/en.po
Labels: 14.0

#1068 Syncing from upstream OCA/server-tools (15.0)
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  README.md
  auto_backup/i18n/es_AR.po
  module_auto_update/__manifest__.py
  module_auto_update/tests/sample_module/i18n/en.po
Labels: 15.0

#1069 Syncing from upstream OCA/server-tools (16.0)
  base_exception/i18n/es_AR.po
Labels: 16.0

#1070 Syncing from upstream OCA/server-tools (14.0)
  README.md
  auditlog/README.rst
  auditlog/__manifest__.py
  auditlog/models/autovacuum.py
  auditlog/readme/USAGE.rst
  auditlog/static/description/index.html
Labels: 14.0

#1072 Syncing from upstream OCA/server-tools (8.0)
  auto_backup/i18n/it.po
  base_search_fuzzy/i18n/it.po
Labels: 8.0

#1073 Syncing from upstream OCA/server-tools (13.0)
  README.md
  database_cleanup/i18n/it.po
  sentry/__init__.py
  sentry/__manifest__.py
  sentry/tests/test_client.py
Labels: 13.0

#1074 Syncing from upstream OCA/server-tools (14.0)
  base_exception/i18n/it.po
  database_cleanup/i18n/it.po
Labels: 14.0

#1075 Syncing from upstream OCA/server-tools (16.0)
  README.md
  requirements.txt
  sentry/README.rst
  sentry/__init__.py
  sentry/__manifest__.py
  sentry/const.py
  sentry/generalutils.py
  sentry/hooks.py
  sentry/i18n/ca.po
  sentry/i18n/sentry.pot
  sentry/i18n/zh_CN.po
  sentry/logutils.py
  sentry/processor.py
  sentry/readme/CONFIGURE.rst
  sentry/readme/CONTRIBUTORS.rst
  sentry/readme/CREDITS.rst
  sentry/readme/DESCRIPTION.rst
  sentry/readme/INSTALL.rst
  sentry/readme/ROADMAP.rst
  sentry/readme/USAGE.rst
  sentry/static/description/icon.png
  sentry/static/description/index.html
  sentry/tests/__init__.py
  sentry/tests/test_client.py
  sentry/tests/test_logutils.py
  session_db/README.rst
  session_db/__init__.py
  session_db/__manifest__.py
  session_db/i18n/session_db.pot
  session_db/pg_session_store.py
  session_db/readme/DESCRIPTION.rst
  session_db/readme/ROADMAP.rst
  session_db/readme/USAGE.rst
  session_db/static/description/icon.png
  session_db/static/description/index.html
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sentry/odoo/addons/sentry
  setup/sentry/setup.py
  setup/session_db/odoo/addons/session_db
  setup/session_db/setup.py
Labels: 16.0

#1076 Syncing from upstream OCA/server-tools (16.0)
  README.md
  auditlog/README.rst
  auditlog/__manifest__.py
  auditlog/models/autovacuum.py
  auditlog/readme/USAGE.rst
  auditlog/static/description/index.html
Labels: 16.0

#1077 Updating server-tools from latest OCA/15.0
  README.md
  auditlog/README.rst
  auditlog/__manifest__.py
  auditlog/models/autovacuum.py
  auditlog/readme/USAGE.rst
  auditlog/static/description/index.html
  auto_backup/__manifest__.py
  requirements.txt
Labels: 15.0

#1078 Syncing from upstream OCA/server-tools (16.0)
  README.md
  session_db/__manifest__.py
  session_db/pg_session_store.py
Labels: 16.0

#1079 Syncing from upstream OCA/server-tools (14.0)
  base_custom_info/i18n/it.po
Labels: 14.0
