Repository brain-tec/server-tools, pull requests merged in 2024-07, with the labels that each got.

#1572 Syncing from upstream OCA/server-tools (17.0)
  .copier-answers.yml
  .eslintrc.yml
  .gitignore
  README.md
  server_action_logging/README.rst
  server_action_logging/__init__.py
  server_action_logging/__manifest__.py
  server_action_logging/i18n/fr.po
  server_action_logging/i18n/pt_BR.po
  server_action_logging/i18n/server_action_logging.pot
  server_action_logging/models/__init__.py
  server_action_logging/models/ir_actions_server.py
  server_action_logging/pyproject.toml
  server_action_logging/readme/CONTRIBUTORS.md
  server_action_logging/readme/DESCRIPTION.md
  server_action_logging/readme/USAGE.md
  server_action_logging/static/description/icon.png
  server_action_logging/static/description/index.html
  server_action_logging/tests/__init__.py
  server_action_logging/tests/test_server_action_logging.py
  server_action_logging/views/ir_actions_server.xml
  setup/_metapackage/pyproject.toml
Labels: 17.0

#1573 Syncing from upstream OCA/server-tools (8.0)
  super_calendar/i18n/it.po
Labels: 8.0

#1574 Syncing from upstream OCA/server-tools (10.0)
  super_calendar/i18n/it.po
Labels: 10.0

#1575 Syncing from upstream OCA/server-tools (16.0)
  excel_import_export/i18n/it.po
Labels: 16.0

#1576 [17.0][MIG] fetchmail_notify_error_to_sender, fetchmail_notify_error_to_sender_test: Migration to 17.0
  fetchmail_notify_error_to_sender/README.rst
  fetchmail_notify_error_to_sender/__init__.py
  fetchmail_notify_error_to_sender/__manifest__.py
  fetchmail_notify_error_to_sender/data/email_template_data.xml
  fetchmail_notify_error_to_sender/i18n/ca.po
  fetchmail_notify_error_to_sender/i18n/de.po
  fetchmail_notify_error_to_sender/i18n/es.po
  fetchmail_notify_error_to_sender/i18n/es_AR.po
  fetchmail_notify_error_to_sender/i18n/fetchmail_notify_error_to_sender.pot
  fetchmail_notify_error_to_sender/i18n/fr.po
  fetchmail_notify_error_to_sender/i18n/hr.po
  fetchmail_notify_error_to_sender/i18n/it.po
  fetchmail_notify_error_to_sender/i18n/pt_BR.po
  fetchmail_notify_error_to_sender/i18n/pt_PT.po
  fetchmail_notify_error_to_sender/i18n/sl.po
  fetchmail_notify_error_to_sender/i18n/tr.po
  fetchmail_notify_error_to_sender/i18n/zh_CN.po
  fetchmail_notify_error_to_sender/models/__init__.py
  fetchmail_notify_error_to_sender/models/fetchmail.py
  fetchmail_notify_error_to_sender/models/mail_thread.py
  fetchmail_notify_error_to_sender/pyproject.toml
  fetchmail_notify_error_to_sender/readme/CONFIGURE.md
  fetchmail_notify_error_to_sender/readme/CONTRIBUTORS.md
  fetchmail_notify_error_to_sender/readme/DESCRIPTION.md
  fetchmail_notify_error_to_sender/static/description/icon.png
  fetchmail_notify_error_to_sender/static/description/index.html
  fetchmail_notify_error_to_sender/views/fetchmail_view.xml
  fetchmail_notify_error_to_sender_test/README.rst
  fetchmail_notify_error_to_sender_test/__init__.py
  fetchmail_notify_error_to_sender_test/__manifest__.py
  fetchmail_notify_error_to_sender_test/i18n/ca.po
  fetchmail_notify_error_to_sender_test/i18n/fetchmail_notify_error_to_sender_test.pot
  fetchmail_notify_error_to_sender_test/pyproject.toml
  fetchmail_notify_error_to_sender_test/readme/CONTRIBUTORS.md
  fetchmail_notify_error_to_sender_test/readme/DESCRIPTION.md
  fetchmail_notify_error_to_sender_test/static/description/icon.png
  fetchmail_notify_error_to_sender_test/static/description/index.html
  fetchmail_notify_error_to_sender_test/tests/__init__.py
  fetchmail_notify_error_to_sender_test/tests/test_fetchmail_notify_error_to_sender.py
Labels: 17.0.project_bo_543

#1577 Syncing from upstream OCA/server-tools (17.0)
  server_action_logging/i18n/fr.po
  server_action_logging/i18n/pt_BR.po
Labels: 17.0

#1578 Syncing from upstream OCA/server-tools (14.0)
  README.md
  database_cleanup/README.rst
  database_cleanup/__manifest__.py
  database_cleanup/models/purge_tables.py
  database_cleanup/static/description/index.html
Labels: 14.0

#1579 Syncing from upstream OCA/server-tools (15.0)
  README.md
  database_cleanup/README.rst
  database_cleanup/__manifest__.py
  database_cleanup/models/purge_tables.py
  database_cleanup/static/description/index.html
Labels: 15.0

#1580 Syncing from upstream OCA/server-tools (16.0)
  README.md
  database_cleanup/README.rst
  database_cleanup/__manifest__.py
  database_cleanup/models/purge_tables.py
  database_cleanup/static/description/index.html
Labels: 16.0

#1581 Syncing from upstream OCA/server-tools (17.0)
  server_action_logging/i18n/it.po
Labels: 17.0

#1582 Syncing from upstream OCA/server-tools (14.0)
  excel_import_export/i18n/it.po
Labels: 14.0

#1583 Syncing from upstream OCA/server-tools (15.0)
  excel_import_export/i18n/it.po
Labels: 15.0

#1584 Syncing from upstream OCA/server-tools (16.0)
  excel_import_export/i18n/it.po
Labels: 16.0

#1585 Syncing from upstream OCA/server-tools (14.0)
  README.md
  database_cleanup/README.rst
  database_cleanup/__manifest__.py
  database_cleanup/models/purge_columns.py
  database_cleanup/readme/CONTRIBUTORS.rst
  database_cleanup/static/description/index.html
Labels: 14.0

#1586 Syncing from upstream OCA/server-tools (15.0)
  README.md
  base_changeset/i18n/base_changeset.pot
  base_changeset/i18n/ca.po
  base_changeset/i18n/es.po
  base_changeset/i18n/it.po
  database_cleanup/README.rst
  database_cleanup/__manifest__.py
  database_cleanup/models/purge_columns.py
  database_cleanup/readme/CONTRIBUTORS.rst
  database_cleanup/static/description/index.html
  session_db/README.rst
  session_db/__manifest__.py
  session_db/readme/ROADMAP.rst
  session_db/static/description/index.html
Labels: 15.0

#1587 Syncing from upstream OCA/server-tools (16.0)
  README.md
  session_db/README.rst
  session_db/__manifest__.py
  session_db/readme/ROADMAP.rst
  session_db/static/description/index.html
Labels: 16.0

#1588 Syncing from upstream OCA/server-tools (15.0)
  database_cleanup/i18n/es_AR.po
Labels: 15.0

#1590 Syncing from upstream OCA/server-tools (14.0)
  README.md
  tracking_manager/README.rst
  tracking_manager/__manifest__.py
  tracking_manager/static/description/index.html
  tracking_manager/tools.py
Labels: 14.0
