Repository brain-tec/server-tools, pull requests merged in 2024-03, with the labels that each got.

#1491 Syncing from upstream OCA/server-tools (17.0)
  README.md
  onchange_helper/README.rst
  onchange_helper/__manifest__.py
  onchange_helper/static/description/index.html
Labels: 17.0

#1493 Syncing from upstream OCA/server-tools (16.0)
  autovacuum_message_attachment/i18n/it.po
Labels: 16.0

#1494 Syncing from upstream OCA/server-tools (10.0)
  html_text/__manifest__.py
Labels: 10.0

#1495 Syncing from upstream OCA/server-tools (9.0)
  base_report_auto_create_qweb/i18n/it.po
Labels: 9.0

#1496 [bt#25178] Backport cron_daylight_saving_time_resistant Module
  cron_daylight_saving_time_resistant/README.rst
  cron_daylight_saving_time_resistant/__init__.py
  cron_daylight_saving_time_resistant/__manifest__.py
  cron_daylight_saving_time_resistant/i18n/cron_daylight_saving_time_resistant.pot
  cron_daylight_saving_time_resistant/i18n/es.po
  cron_daylight_saving_time_resistant/i18n/it.po
  cron_daylight_saving_time_resistant/models/__init__.py
  cron_daylight_saving_time_resistant/models/ir_cron.py
  cron_daylight_saving_time_resistant/readme/CONFIGURE.rst
  cron_daylight_saving_time_resistant/readme/CONTRIBUTORS.rst
  cron_daylight_saving_time_resistant/readme/DESCRIPTION.rst
  cron_daylight_saving_time_resistant/static/description/icon.png
  cron_daylight_saving_time_resistant/static/description/index.html
  cron_daylight_saving_time_resistant/tests/__init__.py
  cron_daylight_saving_time_resistant/tests/test_dst.py
  cron_daylight_saving_time_resistant/views/ir_cron_views.xml
  setup/cron_daylight_saving_time_resistant/odoo/addons/cron_daylight_saving_time_resistant
  setup/cron_daylight_saving_time_resistant/setup.py
Labels: 15.0

#1497 Syncing from upstream OCA/server-tools (13.0)
  base_import_odoo/i18n/it.po
Labels: 13.0

#1498 Syncing from upstream OCA/server-tools (14.0)
  base_import_odoo/i18n/it.po
Labels: 14.0

#1499 Syncing from upstream OCA/server-tools (8.0)
  password_security/i18n/it.po
Labels: 8.0

#1500 Syncing from upstream OCA/server-tools (9.0)
  kpi/i18n/it.po
  password_security/i18n/it.po
Labels: 9.0
