Repository brain-tec/server-tools, pull requests merged in 2024-02, with the labels that each got.

#1436 Syncing from upstream OCA/server-tools (16.0)
  README.md
  attachment_synchronize/README.rst
  attachment_synchronize/__init__.py
  attachment_synchronize/__manifest__.py
  attachment_synchronize/data/cron.xml
  attachment_synchronize/demo/attachment_synchronize_task_demo.xml
  attachment_synchronize/i18n/attachment_synchronize.pot
  attachment_synchronize/models/__init__.py
  attachment_synchronize/models/attachment_queue.py
  attachment_synchronize/models/attachment_synchronize_task.py
  attachment_synchronize/models/storage_backend.py
  attachment_synchronize/readme/CONTRIBUTORS.rst
  attachment_synchronize/readme/DESCRIPTION.rst
  attachment_synchronize/readme/USAGE.rst
  attachment_synchronize/security/ir.model.access.csv
  attachment_synchronize/static/description/export_task.png
  attachment_synchronize/static/description/icon.png
  attachment_synchronize/static/description/import_task.png
  attachment_synchronize/static/description/index.html
  attachment_synchronize/tests/__init__.py
  attachment_synchronize/tests/common.py
  attachment_synchronize/tests/test_export.py
  attachment_synchronize/tests/test_import.py
  attachment_synchronize/views/attachment_queue_views.xml
  attachment_synchronize/views/attachment_synchronize_task_views.xml
  attachment_synchronize/views/storage_backend_views.xml
  base_name_search_improved/i18n/base_name_search_improved.pot
  base_name_search_improved/i18n/ca.po
  base_name_search_improved/i18n/de.po
  base_name_search_improved/i18n/es.po
  base_name_search_improved/i18n/es_ES.po
  base_name_search_improved/i18n/eu.po
  base_name_search_improved/i18n/fi.po
  base_name_search_improved/i18n/fr.po
  base_name_search_improved/i18n/hr.po
  base_name_search_improved/i18n/hr_HR.po
  base_name_search_improved/i18n/it.po
  base_name_search_improved/i18n/nb_NO.po
  base_name_search_improved/i18n/nl.po
  base_name_search_improved/i18n/pt_BR.po
  base_name_search_improved/i18n/sl.po
  base_name_search_improved/i18n/tr.po
  base_name_search_improved/i18n/tr_TR.po
  base_name_search_improved/i18n/zh_CN.po
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/attachment_synchronize/odoo/addons/attachment_synchronize
  setup/attachment_synchronize/setup.py
Labels: 16.0

#1437 Syncing from upstream OCA/server-tools (16.0)
  attachment_synchronize/i18n/it.po
  cron_daylight_saving_time_resistant/i18n/it.po
Labels: 16.0

#1441 [16.0][IMP] base_view_inheritance_extension: attrs_domain_add
  base_view_inheritance_extension/__manifest__.py
  base_view_inheritance_extension/models/ir_ui_view.py
  base_view_inheritance_extension/readme/CONTRIBUTORS.rst
  base_view_inheritance_extension/readme/USAGE.rst
  base_view_inheritance_extension/tests/test_base_view_inheritance_extension.py
Labels: 16.0.project_sa_690.t145462

#1443 Syncing from upstream OCA/server-tools (17.0)
  README.md
  base_view_inheritance_extension/README.rst
  base_view_inheritance_extension/__init__.py
  base_view_inheritance_extension/__manifest__.py
  base_view_inheritance_extension/demo/ir_ui_view.xml
  base_view_inheritance_extension/i18n/base_view_inheritance_extension.pot
  base_view_inheritance_extension/i18n/ca.po
  base_view_inheritance_extension/i18n/de.po
  base_view_inheritance_extension/i18n/es.po
  base_view_inheritance_extension/i18n/es_AR.po
  base_view_inheritance_extension/i18n/hr.po
  base_view_inheritance_extension/i18n/it.po
  base_view_inheritance_extension/i18n/sl.po
  base_view_inheritance_extension/i18n/tr.po
  base_view_inheritance_extension/models/__init__.py
  base_view_inheritance_extension/models/ir_ui_view.py
  base_view_inheritance_extension/pyproject.toml
  base_view_inheritance_extension/readme/CONTRIBUTORS.md
  base_view_inheritance_extension/readme/DESCRIPTION.md
  base_view_inheritance_extension/readme/ROADMAP.md
  base_view_inheritance_extension/readme/USAGE.md
  base_view_inheritance_extension/static/description/icon.png
  base_view_inheritance_extension/static/description/index.html
  base_view_inheritance_extension/tests/__init__.py
  base_view_inheritance_extension/tests/test_base_view_inheritance_extension.py
  requirements.txt
  scheduler_error_mailer/README.rst
  scheduler_error_mailer/__init__.py
  scheduler_error_mailer/__manifest__.py
  scheduler_error_mailer/data/ir_cron_email_tpl.xml
  scheduler_error_mailer/demo/ir_cron_demo.xml
  scheduler_error_mailer/hooks.py
  scheduler_error_mailer/i18n/de.po
  scheduler_error_mailer/i18n/es.po
  scheduler_error_mailer/i18n/es_AR.po
  scheduler_error_mailer/i18n/fr.po
  scheduler_error_mailer/i18n/hr.po
  scheduler_error_mailer/i18n/pt.po
  scheduler_error_mailer/i18n/pt_BR.po
  scheduler_error_mailer/i18n/scheduler_error_mailer.pot
  scheduler_error_mailer/i18n/sl.po
  scheduler_error_mailer/i18n/zh_CN.po
  scheduler_error_mailer/images/scheduler_error_mailer.jpg
  scheduler_error_mailer/models/__init__.py
  scheduler_error_mailer/models/ir_cron.py
  scheduler_error_mailer/pyproject.toml
  scheduler_error_mailer/readme/CONFIGURE.md
  scheduler_error_mailer/readme/CONTRIBUTORS.md
  scheduler_error_mailer/readme/DESCRIPTION.md
  scheduler_error_mailer/static/description/icon.png
  scheduler_error_mailer/static/description/index.html
  scheduler_error_mailer/tests/__init__.py
  scheduler_error_mailer/tests/test_scheduler_error_mailer.py
  scheduler_error_mailer/views/ir_cron.xml
  setup/_metapackage/pyproject.toml
Labels: 17.0

#1445 Syncing from upstream OCA/server-tools (15.0)
  README.md
  upgrade_analysis/README.rst
  upgrade_analysis/__manifest__.py
  upgrade_analysis/models/upgrade_comparison_config.py
  upgrade_analysis/readme/DESCRIPTION.rst
  upgrade_analysis/static/description/index.html
Labels: 15.0

#1446 Syncing from upstream OCA/server-tools (16.0)
  README.md
  upgrade_analysis/README.rst
  upgrade_analysis/__manifest__.py
  upgrade_analysis/odoo_patch/addons/__init__.py
  upgrade_analysis/odoo_patch/addons/sale_quotation_builder/__init__.py
  upgrade_analysis/static/description/index.html
Labels: 16.0

#1448 Syncing from upstream OCA/server-tools (12.0)
  excel_import_export/i18n/it.po
Labels: 12.0

#1449 Syncing from upstream OCA/server-tools (14.0)
  README.md
  dbfilter_from_header/README.rst
  dbfilter_from_header/__manifest__.py
  dbfilter_from_header/override.py
  dbfilter_from_header/static/description/index.html
  excel_import_export/i18n/it.po
  fetchmail_notify_error_to_sender/i18n/it.po
  model_read_only/i18n/it.po
  module_analysis/i18n/it.po
Labels: 14.0

#1451 Syncing from upstream OCA/server-tools (17.0)
  dbfilter_from_header/i18n/it.po
  jsonifier/i18n/it.po
  module_change_auto_install/i18n/it.po
  scheduler_error_mailer/i18n/it.po
Labels: 17.0

#1452 Syncing from upstream OCA/server-tools (17.0)
  scheduler_error_mailer/i18n/it.po
Labels: 17.0

#1453 Syncing from upstream OCA/server-tools (16.0)
  README.md
  base_view_inheritance_extension/README.rst
  base_view_inheritance_extension/__manifest__.py
  base_view_inheritance_extension/models/ir_ui_view.py
  base_view_inheritance_extension/readme/CONTRIBUTORS.rst
  base_view_inheritance_extension/readme/USAGE.rst
  base_view_inheritance_extension/static/description/index.html
  base_view_inheritance_extension/tests/test_base_view_inheritance_extension.py
Labels: 16.0

#1455 Syncing from upstream OCA/server-tools (16.0)
  autovacuum_message_attachment/i18n/it.po
  url_attachment_search_fuzzy/i18n/it.po
Labels: 16.0

#1456 Syncing from upstream OCA/server-tools (12.0)
  README.md
  base_model_restrict_update/README.rst
  base_model_restrict_update/__manifest__.py
  base_model_restrict_update/i18n/base_model_restrict_update.po
  base_model_restrict_update/i18n/base_model_restrict_update.pot
  base_model_restrict_update/i18n/ja.po
  base_model_restrict_update/i18n/ja_JP.po
  base_model_restrict_update/models/ir_model.py
  base_model_restrict_update/models/ir_model_access.py
  base_model_restrict_update/readme/CONFIGURE.rst
  base_model_restrict_update/static/description/index.html
  base_model_restrict_update/tests/test_base_model_restrict_update.py
  base_model_restrict_update/views/ir_model_views.xml
  excel_import_export/README.rst
  excel_import_export/__manifest__.py
  excel_import_export/i18n/excel_import_export.pot
  excel_import_export/i18n/it.po
  excel_import_export/i18n/tr.po
  excel_import_export/i18n/zh_CN.po
  excel_import_export/models/common.py
  excel_import_export/models/xlsx_export.py
  excel_import_export/models/xlsx_import.py
  excel_import_export/static/description/index.html
  excel_import_export/wizard/export_xlsx_wizard.py
  excel_import_export/wizard/export_xlsx_wizard.xml
  excel_import_export_demo/README.rst
  excel_import_export_demo/__manifest__.py
  excel_import_export_demo/i18n/excel_import_export_demo.pot
  excel_import_export_demo/i18n/tr.po
  excel_import_export_demo/i18n/zh_CN.po
  excel_import_export_demo/import_export_sale_order/actions.xml
  excel_import_export_demo/static/description/index.html
  excel_import_export_demo/tests/test_xlsx_import_export.py
  sentry/README.rst
  sentry/__manifest__.py
  sentry/hooks.py
  sentry/static/description/index.html
Labels: 12.0

#1457 Syncing from upstream OCA/server-tools (15.0)
  README.md
  base_fontawesome/README.rst
  base_fontawesome/__manifest__.py
  base_fontawesome/static/description/index.html
  base_fontawesome/static/src/css/fontawesome.css
Labels: 15.0

#1459 Syncing from upstream OCA/server-tools (13.0)
  module_analysis/i18n/it.po
Labels: 13.0

#1460 Syncing from upstream OCA/server-tools (14.0)
  base_name_search_improved/i18n/it.po
  excel_import_export/i18n/it.po
Labels: 14.0

#1461 Syncing from upstream OCA/server-tools (15.0)
  excel_import_export/i18n/it.po
  module_analysis/i18n/it.po
Labels: 15.0

#1462 Syncing from upstream OCA/server-tools (16.0)
  attachment_queue/i18n/es.po
  attachment_synchronize/i18n/es.po
  autovacuum_message_attachment/i18n/es.po
Labels: 16.0

#1463 Syncing from upstream OCA/server-tools (17.0)
  database_cleanup/i18n/it.po
Labels: 17.0

#1464 Syncing from upstream OCA/server-tools (12.0)
  README.md
  database_cleanup/__manifest__.py
  database_cleanup/tests/test_database_cleanup.py
  dbfilter_from_header/README.rst
  dbfilter_from_header/__manifest__.py
  dbfilter_from_header/override.py
  dbfilter_from_header/static/description/index.html
Labels: 12.0

#1465 Syncing from upstream OCA/server-tools (16.0)
  autovacuum_message_attachment/i18n/es.po
Labels: 16.0

#1466 Syncing from upstream OCA/server-tools (12.0)
  README.md
  module_auto_update/README.rst
  module_auto_update/__manifest__.py
  module_auto_update/static/description/index.html
  module_auto_update/tests/test_addon_hash.py
Labels: 12.0

#1467 Syncing from upstream OCA/server-tools (13.0)
  README.md
  module_auto_update/README.rst
  module_auto_update/__manifest__.py
  module_auto_update/static/description/index.html
  module_auto_update/tests/test_addon_hash.py
Labels: 13.0

#1468 Syncing from upstream OCA/server-tools (14.0)
  README.md
  module_auto_update/README.rst
  module_auto_update/__manifest__.py
  module_auto_update/static/description/index.html
  module_auto_update/tests/test_addon_hash.py
Labels: 14.0

#1469 Syncing from upstream OCA/server-tools (15.0)
  README.md
  sequence_python/README.rst
  sequence_python/__init__.py
  sequence_python/__manifest__.py
  sequence_python/i18n/ca.po
  sequence_python/i18n/es_AR.po
  sequence_python/i18n/sequence_python.pot
  sequence_python/models/__init__.py
  sequence_python/models/ir_sequence.py
  sequence_python/readme/CONTRIBUTORS.rst
  sequence_python/readme/DESCRIPTION.rst
  sequence_python/readme/USAGE.rst
  sequence_python/static/description/icon.png
  sequence_python/static/description/index.html
  sequence_python/tests/__init__.py
  sequence_python/tests/test_ir_sequence.py
  sequence_python/views/ir_sequence.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sequence_python/odoo/addons/sequence_python
  setup/sequence_python/setup.py
Labels: 15.0

#1470 Syncing from upstream OCA/server-tools (16.0)
  README.md
  autovacuum_message_attachment/i18n/es.po
  base_fontawesome/README.rst
  base_fontawesome/__manifest__.py
  base_fontawesome/static/description/index.html
  base_fontawesome/static/src/css/fontawesome.css
  base_sequence_default/i18n/es.po
  cron_daylight_saving_time_resistant/i18n/es.po
  excel_import_export/i18n/es.po
  excel_import_export_demo/README.rst
  excel_import_export_demo/__manifest__.py
  excel_import_export_demo/i18n/es.po
  excel_import_export_demo/report_action/partner_list/report_partner_list.xml
  excel_import_export_demo/static/description/index.html
  excel_import_export_unidecode/i18n/es.po
  iap_alternative_provider/i18n/es.po
  module_auto_update/README.rst
  module_auto_update/__manifest__.py
  module_auto_update/static/description/index.html
  module_auto_update/tests/test_addon_hash.py
  scheduler_error_mailer/i18n/es.po
  tracking_manager/i18n/es.po
Labels: 16.0

#1471 Syncing from upstream OCA/server-tools (17.0)
  base_exception/i18n/es.po
  base_exception/i18n/it.po
  jsonifier/i18n/it.po
Labels: 17.0

#1474 Syncing from upstream OCA/server-tools (14.0)
  base_import_odoo/i18n/it.po
Labels: 14.0

#1476 Syncing from upstream OCA/server-tools (16.0)
  README.md
  auditlog/README.rst
  auditlog/__manifest__.py
  auditlog/models/rule.py
  auditlog/static/description/index.html
  auditlog/tests/test_auditlog.py
  database_cleanup/README.rst
  database_cleanup/__manifest__.py
  database_cleanup/models/purge_columns.py
  database_cleanup/readme/CONTRIBUTORS.rst
  database_cleanup/static/description/index.html
Labels: 16.0

#1477 Syncing from upstream OCA/server-tools (12.0)
  README.md
  autovacuum_message_attachment/i18n/autovacuum_message_attachment.pot
  autovacuum_message_attachment/i18n/fr.po
  base_changeset/i18n/base_changeset.pot
  base_changeset/i18n/es.po
  nsca_client/README.rst
  nsca_client/__init__.py
  nsca_client/__manifest__.py
  nsca_client/demo/demo_data.xml
  nsca_client/i18n/fr.po
  nsca_client/i18n/nsca_client.pot
  nsca_client/models/__init__.py
  nsca_client/models/nsca_check.py
  nsca_client/models/nsca_server.py
  nsca_client/readme/CONFIGURE.rst
  nsca_client/readme/CONTRIBUTORS.rst
  nsca_client/readme/DESCRIPTION.rst
  nsca_client/readme/INSTALL.rst
  nsca_client/security/ir.model.access.csv
  nsca_client/static/description/check.png
  nsca_client/static/description/icon.png
  nsca_client/static/description/index.html
  nsca_client/static/description/server.png
  nsca_client/tests/__init__.py
  nsca_client/tests/test_nsca.py
  nsca_client/views/nsca_check.xml
  nsca_client/views/nsca_menu.xml
  nsca_client/views/nsca_server.xml
  scheduler_error_mailer/i18n/de.po
  scheduler_error_mailer/i18n/es.po
  scheduler_error_mailer/i18n/fr.po
  scheduler_error_mailer/i18n/hr.po
  scheduler_error_mailer/i18n/pt.po
  scheduler_error_mailer/i18n/pt_BR.po
  scheduler_error_mailer/i18n/scheduler_error_mailer.pot
  scheduler_error_mailer/i18n/sl.po
  scheduler_error_mailer/i18n/zh_CN.po
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/nsca_client/odoo/addons/nsca_client
  setup/nsca_client/setup.py
Labels: 12.0

#1478 Syncing from upstream OCA/server-tools (14.0)
  README.md
  session_db/README.rst
  session_db/__manifest__.py
  session_db/pg_session_store.py
  session_db/static/description/index.html
  session_db/tests/__init__.py
  session_db/tests/test_pg_session_store.py
Labels: 14.0

#1479 Syncing from upstream OCA/server-tools (15.0)
  README.md
  module_auto_update/README.rst
  module_auto_update/__manifest__.py
  module_auto_update/static/description/index.html
  module_auto_update/tests/test_addon_hash.py
Labels: 15.0

#1481 Syncing from upstream OCA/server-tools (12.0)
  README.md
  module_analysis/README.rst
  module_analysis/__init__.py
  module_analysis/__manifest__.py
  module_analysis/data/ir_cron.xml
  module_analysis/i18n/module_analysis.pot
  module_analysis/i18n/zh_CN.po
  module_analysis/models/__init__.py
  module_analysis/models/base_module_update.py
  module_analysis/models/ir_module_module.py
  module_analysis/post_init_hook.py
  module_analysis/readme/CONFIGURE.rst
  module_analysis/static/description/index.html
  module_analysis/tests/test_module.py
  module_analysis/views/view_base_module_update.xml
  profiler/README.rst
  profiler/__manifest__.py
  profiler/i18n/profiler.pot
  profiler/static/description/index.html
  profiler/static/src/js/tour.js
  profiler/tests/__init__.py
  profiler/tests/test_profiling.py
  profiler/tests/test_profiling_ui.py
  profiler/views/assets.xml
Labels: 12.0

#1482 Syncing from upstream OCA/server-tools (14.0)
  README.md
  autovacuum_message_attachment/i18n/autovacuum_message_attachment.pot
  autovacuum_message_attachment/i18n/ca.po
  autovacuum_message_attachment/i18n/es_AR.po
  autovacuum_message_attachment/i18n/fr.po
  profiler/README.rst
  profiler/__init__.py
  profiler/__manifest__.py
  profiler/hooks.py
  profiler/i18n/profiler.pot
  profiler/models/__init__.py
  profiler/models/profiler_profile.py
  profiler/readme/CONTRIBUTORS.rst
  profiler/readme/DESCRIPTION.rst
  profiler/readme/INSTALL.rst
  profiler/readme/USAGE.rst
  profiler/security/ir.model.access.csv
  profiler/static/description/icon.png
  profiler/static/description/index.html
  profiler/tests/__init__.py
  profiler/tests/test_profiling.py
  profiler/views/profiler_profile_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/profiler/odoo/addons/profiler
  setup/profiler/setup.py
Labels: 14.0

#1483 Syncing from upstream OCA/server-tools (13.0)
  README.md
  module_analysis/README.rst
  module_analysis/__init__.py
  module_analysis/__manifest__.py
  module_analysis/data/ir_cron.xml
  module_analysis/i18n/it.po
  module_analysis/i18n/module_analysis.pot
  module_analysis/i18n/zh_CN.po
  module_analysis/models/__init__.py
  module_analysis/models/base_module_update.py
  module_analysis/models/ir_module_module.py
  module_analysis/post_init_hook.py
  module_analysis/readme/CONFIGURE.rst
  module_analysis/static/description/index.html
  module_analysis/tests/test_module.py
  module_analysis/views/view_base_module_update.xml
Labels: 13.0

#1484 Syncing from upstream OCA/server-tools (9.0)
  configuration_helper/i18n/it.po
Labels: 9.0

#1485 Syncing from upstream OCA/server-tools (10.0)
  configuration_helper/i18n/it.po
Labels: 10.0

#1486 Syncing from upstream OCA/server-tools (11.0)
  configuration_helper/i18n/it.po
Labels: 11.0

#1487 Syncing from upstream OCA/server-tools (12.0)
  configuration_helper/i18n/it.po
Labels: 12.0

#1488 Syncing from upstream OCA/server-tools (13.0)
  configuration_helper/i18n/it.po
Labels: 13.0

#1489 Syncing from upstream OCA/server-tools (14.0)
  configuration_helper/i18n/it.po
Labels: 14.0
