Repository brain-tec/server-tools, pull requests merged in 2024-01, with the labels that each got.

#1398 Syncing from upstream OCA/server-tools (9.0)
  keychain/__openerp__.py
  keychain/static/description/icon.png
  mail_environment/__openerp__.py
  mail_environment/static/description/icon.png
  server_environment/__openerp__.py
  server_environment/static/description/icon.png
  server_environment_files_sample/__openerp__.py
  server_environment_files_sample/static/description/icon.png
  server_environment_ir_config_parameter/__openerp__.py
  server_environment_ir_config_parameter/static/description/icon.png
Labels: 9.0

#1399 Syncing from upstream OCA/server-tools (14.0)
  base_name_search_improved/i18n/it.po
Labels: 14.0

#1401 Syncing from upstream OCA/server-tools (8.0)
  auto_backup/i18n/it.po
  scheduler_error_mailer/i18n/it.po
Labels: 8.0

#1402 Syncing from upstream OCA/server-tools (9.0)
  auto_backup/i18n/it.po
Labels: 9.0

#1403 Syncing from upstream OCA/server-tools (10.0)
  auto_backup/i18n/it.po
  users_ldap_mail/i18n/it.po
Labels: 10.0

#1404 Syncing from upstream OCA/server-tools (11.0)
  auto_backup/i18n/it.po
Labels: 11.0

#1405 Syncing from upstream OCA/server-tools (12.0)
  auto_backup/i18n/it.po
  excel_import_export/i18n/it.po
Labels: 12.0

#1406 Syncing from upstream OCA/server-tools (13.0)
  auto_backup/i18n/it.po
Labels: 13.0

#1407 Syncing from upstream OCA/server-tools (14.0)
  auto_backup/i18n/it.po
Labels: 14.0

#1408 Syncing from upstream OCA/server-tools (16.0)
  auto_backup/i18n/it.po
  base_cron_exclusion/i18n/it.po
  base_search_fuzzy/i18n/it.po
  excel_import_export_unidecode/i18n/it.po
  html_text/i18n/it.po
  iap_alternative_provider/i18n/it.po
  rpc_helper/i18n/it.po
  scheduler_error_mailer/i18n/it.po
Labels: 16.0

#1409 Syncing from upstream OCA/server-tools (10.0)
  password_security/i18n/it.po
Labels: 10.0

#1410 Syncing from upstream OCA/server-tools (16.0)
  README.md
  base_name_search_improved/i18n/it.po
  module_change_auto_install/README.rst
  module_change_auto_install/__manifest__.py
  module_change_auto_install/patch.py
  module_change_auto_install/static/description/index.html
Labels: 16.0

#1411 Syncing from upstream OCA/server-tools (8.0)
  module_prototyper/i18n/it.po
Labels: 8.0

#1412 Syncing from upstream OCA/server-tools (9.0)
  module_prototyper/i18n/it.po
Labels: 9.0

#1413 Syncing from upstream OCA/server-tools (10.0)
  module_prototyper/i18n/it.po
Labels: 10.0

#1414 Syncing from upstream OCA/server-tools (12.0)
  base_model_restrict_update/i18n/ja.po
Labels: 12.0

#1415 Syncing from upstream OCA/server-tools (14.0)
  database_cleanup/i18n/it.po
  module_prototyper/i18n/it.po
Labels: 14.0

#1416 Syncing from upstream OCA/server-tools (16.0)
  base_search_fuzzy/i18n/it.po
  iap_alternative_provider/i18n/it.po
Labels: 16.0

#1417 Syncing from upstream OCA/server-tools (12.0)
  excel_import_export/i18n/it.po
Labels: 12.0

#1418 Syncing from upstream OCA/server-tools (14.0)
  base_sequence_option/i18n/it.po
  excel_import_export/i18n/it.po
Labels: 14.0

#1420 Syncing from upstream OCA/server-tools (16.0)
  base_sequence_option/i18n/it.po
  base_time_window/i18n/it.po
  excel_import_export/i18n/it.po
  excel_import_export_demo/i18n/it.po
Labels: 16.0

#1421 Syncing from upstream OCA/server-tools (8.0)
  database_cleanup/i18n/it.po
Labels: 8.0

#1422 Syncing from upstream OCA/server-tools (12.0)
  excel_import_export/i18n/it.po
Labels: 12.0

#1423 Syncing from upstream OCA/server-tools (14.0)
  auditlog/i18n/it.po
  database_cleanup/i18n/it.po
Labels: 14.0

#1424 Syncing from upstream OCA/server-tools (16.0)
  auditlog/i18n/it.po
  base_exception/i18n/it.po
  database_cleanup/i18n/it.po
  excel_import_export/i18n/it.po
  jsonifier/i18n/it.po
Labels: 16.0

#1425 [t141292] avoid m2m multi-company issue
  auditlog/models/rule.py
Labels: 15.0.project_ge_578

#1427 Syncing from upstream OCA/server-tools (16.0)
  attachment_queue/i18n/it.po
  auto_backup/i18n/it.po
  database_cleanup/i18n/it.po
Labels: 16.0

#1429 Syncing from upstream OCA/server-tools (12.0)
  excel_import_export/i18n/it.po
Labels: 12.0

#1435 Syncing from upstream OCA/server-tools (16.0)
  README.md
  cron_daylight_saving_time_resistant/README.rst
  cron_daylight_saving_time_resistant/__init__.py
  cron_daylight_saving_time_resistant/__manifest__.py
  cron_daylight_saving_time_resistant/i18n/cron_daylight_saving_time_resistant.pot
  cron_daylight_saving_time_resistant/models/__init__.py
  cron_daylight_saving_time_resistant/models/ir_cron.py
  cron_daylight_saving_time_resistant/readme/CONFIGURE.rst
  cron_daylight_saving_time_resistant/readme/CONTRIBUTORS.rst
  cron_daylight_saving_time_resistant/readme/DESCRIPTION.rst
  cron_daylight_saving_time_resistant/static/description/icon.png
  cron_daylight_saving_time_resistant/static/description/index.html
  cron_daylight_saving_time_resistant/tests/__init__.py
  cron_daylight_saving_time_resistant/tests/test_dst.py
  cron_daylight_saving_time_resistant/views/ir_cron_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/cron_daylight_saving_time_resistant/odoo/addons/cron_daylight_saving_time_resistant
  setup/cron_daylight_saving_time_resistant/setup.py
Labels: 16.0
